### ISSUE TITLE
THANK YOU VERY MUCH!

### ISSUE THREAD

**Issue by 1c7** [eush77/ass-parser#2]
I was using Electron.js trying to build a desktop client(Mac+Windows) that parse ASS subtitlte file.
(the propose of the project is use Google Translate process SRT and ASS file)

your code work and very helpful,THANK YOU VERY MUCH!
I wonder why such useful modules have so little start/fork.

I am building this side project for fun. 
Thanks again!

Star+Fork+Follow!

**Comment by 1c7** [comment]
you can close this issue whenever you want :D

**Comment by eush77** [comment]
Thank you!
That's very nice to hear.
